### ISSUE TITLE
request.cookies does not exist

### ISSUE THREAD

**Issue by antoinemadec** [totocaca69/zulipbot#1]
@T3lchar , I rebased the **ytplay** branch with the latest commits from **main**.
However, the ```request.cookies``` that you are using cannot be found.

I added the request ```request``` revision I am using in the requirements (as well as bs4).
**Could you please take a look at it?**

A solution might be to use the youtube API instead of scrapping the html.

**Comment by jrmsgr** [comment]
Hey Antoine, 

I addressed the issue in my latests commits and updated **requirements.txt** appropriately. Hope it works this time !
